Build checkout page
SD-0224/frontend-final-3 pull request #103
Opened 2024-04-27 19:48 UTC by ferassmohana

2024-04-27 19:56 UTC, mahmoud-alragabi requested changes

2024-04-27 19:56 UTC, mahmoud-alragabi commented on src/components/payment-section/components/payment-bottom/PaymentBottom.jsx
>            <PaymentBottomItem {...{ handleChange, selectedValue, title, src }} />
needs key

2024-04-27 19:56 UTC, mahmoud-alragabi commented on src/pages/checkout/CheckoutPage.jsx
> +        </Box>
can be broken to smaller components

2024-04-27 22:55 UTC, ileenshaar approved these changes

2024-04-28 08:56 UTC, mahmoud-alragabi approved these changes

2024-04-28 08:56 UTC, merged