Build contexts
SD-0224/frontend-final-3 pull request #107
Opened 2024-05-02 12:37 UTC by ferassmohana

2024-05-02 12:47 UTC, ileenshaar approved these changes

2024-05-02 17:24 UTC, mahmoud-alragabi requested changes
I think it would be better if we had a global context provider that has both the user and cartProducts since we're not using the providers anywhere else but to wrap the router

2024-05-02 17:24 UTC, mahmoud-alragabi commented on src/components/products-table/ProductsTable.jsx
> +  }, [products, isRemove]);
rename  ```isRemove```  to  ```showRemoveButton```

2024-05-02 17:24 UTC, mahmoud-alragabi commented on src/contexts/ProductsContextProvider.jsx
rename to ```CartProductsContext```

2024-05-02 17:24 UTC, mahmoud-alragabi commented on src/contexts/UserContextProvider.jsx
rename variables to users

2024-05-03 23:37 UTC, mahmoud-alragabi approved these changes

2024-05-03 23:37 UTC, merged