My orders
SD-0224/frontend-final-3 pull request #108
Opened 2024-05-02 15:23 UTC by ileenshaar

2024-05-02 17:53 UTC, mahmoud-alragabi requested changes

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/accordion-component/AccordionComponent.jsx
> +          isExpandIcon && (
rename to ```showExpandIcon```

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/fetch-url/FetchUrl.js
great module, this should be in modules, and should have a better name than fetch URL i's too vague

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/ProfileSidebar.jsx
> +  setselectedOrderId,
rename to ```setSelectedOrderId```

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/ProfileSidebar.jsx
> +        ? SidebarOptions[newValue].label.toLowerCase().split(" ").join("-")
should have this whole operation in a clearly named variable, or be it's own function

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/ProfileSidebar.jsx
> +      option.label.toLowerCase().split(" ").join("-").includes(newPath)
should be in a function

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/components/tab-navigation/TabNavigation.jsx
> +          <Tab
needs a key

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/pages/my-cart/MyCart.jsx
> +            />
don't use href use router links

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/pages/user-profile/UserProfile.jsx
> +        const fetchedData = await fetchData("orders");
i think ```fetchedOrders``` would be a better name

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/pages/user-profile/UserProfile.jsx
> +};
can definitely be broken down to smaller components

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/pages/user-profile/components/items-ordered/ItemsOrdered.jsx
> +        handleTabClick={() => console.log("tab clicked")}
remove the ```console.log``` it's a bad practice

2024-05-02 17:53 UTC, mahmoud-alragabi commented on src/pages/user-profile/components/my-orders/components/orders-table/OrdersTable.jsx
> +export function OrdersTable({ ordertablegrid, order, onOrderClick, total }) {
camel case ```orderTableGrid```

2024-05-03 07:53 UTC, mahmoud-alragabi approved these changes

2024-05-03 07:56 UTC, ferassmohana approved these changes

2024-05-03 08:12 UTC, merged