Build breadcrumb
SD-0224/frontend-final-3 pull request #109
Opened 2024-05-02 19:41 UTC by ferassmohana

2024-05-02 20:18 UTC, mahmoud-alragabi requested changes

2024-05-02 20:18 UTC, mahmoud-alragabi commented on src/components/breadcrumbs/Breadcrumbs.jsx
> +    const pathnames = pathname.split("/").filter((x) => x).map(item => item.replace("-", " "));
the operation on path name should be a function

2024-05-02 22:07 UTC, mahmoud-alragabi approved these changes

2024-05-03 07:57 UTC, ileenshaar approved these changes

2024-05-03 08:15 UTC, merged