Build input component
SD-0224/frontend-final-3 pull request #4
Opened 2024-04-03 22:43 UTC by ferassmohana

The name of this component is CustomInput, and it consists of two files:

- CustomInput.jsx
- CustomInput.module.css

This component gives us the advantage of having input with the common styles, and also it gives us the chance to add icons or label.

2024-04-03 22:55 UTC, mahmoud-alragabi requested changes

2024-04-03 22:55 UTC, mahmoud-alragabi commented on src/components/CustomInput/CustomInput.jsx
> +        <div className={styles.input_wrapp}>
don't use snake case in naming classes use camel case

2024-04-03 22:55 UTC, mahmoud-alragabi commented on src/components/CustomInput/CustomInput.jsx
> +export const CustomInput = ({ ...props }) => {
why are you spreading props into a new object then using it, you should extract the individual props like this ```{ label }```

2024-04-03 22:55 UTC, mahmoud-alragabi commented on src/components/CustomInput/CustomInput.module.css
again use camel case

2024-04-03 22:58 UTC, mahmoud-alragabi requested changes

2024-04-03 22:58 UTC, mahmoud-alragabi commented on src/components/CustomInput/CustomInput.jsx
> +                <label for={props.name} className={styles.input_label}>
can't use for in jsx, replace it with htmlFor

2024-04-04 08:34 UTC, mahmoud-alragabi requested changes

2024-04-04 08:34 UTC, mahmoud-alragabi commented on src/components/CustomInput/CustomInput.jsx
> +                    name={props.name}
label for is bound to element id attribute not the name attribute, you should replace name with id here

2024-04-04 09:47 UTC, ileenshaar approved these changes

2024-04-04 13:34 UTC, merged