Profile sidebar
SD-0224/frontend-final-3 pull request #50
Opened 2024-04-13 16:57 UTC by ileenshaar

2024-04-13 17:18 UTC, mahmoud-alragabi requested changes

2024-04-13 17:18 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/profile-sidebar.module.css
> +}
never do !important in css, find another way

2024-04-13 17:18 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/profile-sidebar.jsx
> +    value === index ? styles.fontColor1B4B66 : styles.fontColor13101E;
change this to be as getBorderColor

2024-04-13 17:18 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/profile-sidebar.jsx
> +  const getBorderColor = (index) => (value === index ? "#1B4B66" : "#000000");
move them out to a module file and import them

2024-04-13 18:47 UTC, mahmoud-alragabi requested changes

2024-04-13 18:47 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/components/tab-content-styles/TabContentStyles.jsx
shouldn't have jsx extension because it doesn't have any jsx in it use js

2024-04-13 18:47 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/components/tab-content-styles/TabContentStyles.jsx
> +  value === index ? styles.fontColor1B4B66 : styles.fontColor13101E;
shouldn't rely on styles, use color values directly

2024-04-13 18:47 UTC, mahmoud-alragabi commented on src/components/profile-sidebar/profile-sidebar.module.css
> +  max-width: none !important;
again don't use !important

2024-04-13 19:29 UTC, mahmoud-alragabi approved these changes

2024-04-14 09:19 UTC, ferassmohana approved these changes

2024-04-14 09:19 UTC, merged