Complete product in cart
SD-0224/frontend-final-3 pull request #61
Opened 2024-04-15 19:15 UTC by ferassmohana

2024-04-15 19:22 UTC, ileenshaar approved these changes

2024-04-16 08:38 UTC, mahmoud-alragabi requested changes

2024-04-16 08:38 UTC, mahmoud-alragabi commented on src/components/product-in-cart/ProductInCart.jsx
>      return (
remove these defaults

2024-04-16 08:38 UTC, mahmoud-alragabi commented on src/components/quantity-counter/QuantitiyCounter.jsx
> +export const QuantityCounter = ({ quantityValue = 0, showText = true }) => {
rename to just quantity, value added to it is redundant

2024-04-16 08:38 UTC, mahmoud-alragabi commented on src/components/quantity-counter/QuantitiyCounter.jsx
>                  <button className={`${styles.counterOperation} ${!value ? styles.disabled : ''}`} type='button' onClick={decreaseHandler}>
save the condition to a variable and use here

2024-04-16 09:57 UTC, mahmoud-alragabi approved these changes

2024-04-16 09:57 UTC, merged