Build drawer component
SD-0224/frontend-final-3 pull request #80
Opened 2024-04-21 12:46 UTC by ferassmohana

2024-04-21 12:48 UTC, ileenshaar approved these changes

2024-04-21 12:56 UTC, mahmoud-alragabi requested changes

2024-04-21 12:56 UTC, mahmoud-alragabi commented on src/layout/components/header/Header.jsx
> +
abstract to it's own component or multiple components if possible

2024-04-22 08:55 UTC, mahmoud-alragabi requested changes

2024-04-22 08:55 UTC, mahmoud-alragabi commented on src/layout/components/header/components/custom-drawer/CustomDrawer.jsx
> +                <FinancialDetails title={"Total"} amount={111.38} total={true} />
these should be passed from the top not hard coded, also the boolean variable total should be isTotal

2024-04-22 10:48 UTC, mahmoud-alragabi approved these changes

2024-04-22 10:48 UTC, merged