User profile
SD-0224/frontend-final-3 pull request #99
Opened 2024-04-25 22:37 UTC by ileenshaar

2024-04-26 20:05 UTC, mahmoud-alragabi requested changes

2024-04-26 20:05 UTC, mahmoud-alragabi commented on src/components/products-table/ProductsTable.jsx
> +      <tr key={index}>
key is better if it would be ```product.id``` it's more unique

2024-04-26 20:05 UTC, mahmoud-alragabi commented on src/pages/user-profile/components/items-ordered/ItemsOrdered.jsx
> +  ];
pass as props

2024-04-26 20:05 UTC, mahmoud-alragabi commented on src/components/products-table/ProductsTable.jsx
can be broken down to smaller components

2024-04-26 20:05 UTC, mahmoud-alragabi commented on src/pages/user-profile/components/my-orders/MyOrders.jsx
> +  ];
pass as props

2024-04-26 20:05 UTC, mahmoud-alragabi commented on src/pages/user-profile/components/my-orders/MyOrders.jsx
> +            return <Typography className={styles.titles}>{title}</Typography>;
needs key

2024-04-26 22:50 UTC, mahmoud-alragabi requested changes
Still have two changes left

2024-04-26 23:19 UTC, ileenshaar commented on src/components/products-table/ProductsTable.jsx
this is not my component

2024-04-27 09:32 UTC, mahmoud-alragabi approved these changes

2024-04-27 14:27 UTC, ferassmohana approved these changes

2024-04-27 14:27 UTC, merged